

movement_csv: "/data/nlahaye/NatureNet/Hammerhead_In/Data_aniMotum_CTCRW_output_predicted_rerouted_non-projected_with_Argosfilter_data.csv"

out_dir: "/data/nlahaye/NatureNet_Env/output"
run_uid: "simple_env"

n_clusters: 150
df_run_uid: "hammerhead_v1"
df_dir: "/data/nlahaye/NatureNet/Hammerhead_Out_v1/"

init_preprocess: False


lon_bounds: [-100.0, -60.0]
lat_bounds: [20, 40]

grid_res_lon: 0.027 #0.027
grid_res_lat: 0.027 #0.027


