import re
import numpy as np
import os
from pprint import pprint

init_states = ["/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_10826_states_abstract_env.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_10830_states_abstract_env.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_10831_states_abstract_env.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_10840_states_abstract_env.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_1385_states_abstract_env.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_23031_states_abstract_env.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_4176_states_abstract_env.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5648_states_abstract_env.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5670_states_abstract_env.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5679_states_abstract_env.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5800_states_abstract_env.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5803_states_abstract_env.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5840_states_abstract_env.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5910_states_abstract_env.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5921_states_abstract_env.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_825_states_abstract_env.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_826_states_abstract_env.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_827_states_abstract_env.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_831_states_abstract_env.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_835_states_abstract_env.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_841_states_abstract_env.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_845_states_abstract_env.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_847_states_abstract_env.pkl"]



actions = ["/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_10826_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_10826__aug10_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_10826__aug1_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_10826__aug2_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_10826__aug3_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_10826__aug4_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_10826__aug5_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_10826__aug6_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_10826__aug7_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_10826__aug8_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_10826__aug9_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_10830_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_10830__aug10_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_10830__aug1_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_10830__aug2_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_10830__aug3_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_10830__aug4_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_10830__aug5_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_10830__aug6_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_10830__aug7_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_10830__aug8_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_10830__aug9_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_10831_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_10831__aug10_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_10831__aug1_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_10831__aug2_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_10831__aug3_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_10831__aug4_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_10831__aug5_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_10831__aug6_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_10831__aug7_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_10831__aug8_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_10831__aug9_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_10840_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_10840__aug10_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_10840__aug1_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_10840__aug2_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_10840__aug3_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_10840__aug4_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_10840__aug5_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_10840__aug6_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_10840__aug7_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_10840__aug8_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_10840__aug9_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_1385_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_1385__aug10_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_1385__aug1_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_1385__aug2_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_1385__aug3_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_1385__aug4_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_1385__aug5_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_1385__aug6_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_1385__aug7_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_1385__aug8_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_1385__aug9_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_23031_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_23031__aug10_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_23031__aug1_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_23031__aug2_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_23031__aug3_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_23031__aug4_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_23031__aug5_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_23031__aug6_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_23031__aug7_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_23031__aug8_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_23031__aug9_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_4176_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_4176__aug10_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_4176__aug1_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_4176__aug2_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_4176__aug3_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_4176__aug4_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_4176__aug5_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_4176__aug6_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_4176__aug7_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_4176__aug8_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_4176__aug9_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5648_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5648__aug10_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5648__aug1_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5648__aug2_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5648__aug3_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5648__aug4_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5648__aug5_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5648__aug6_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5648__aug7_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5648__aug8_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5648__aug9_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5670_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5670__aug10_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5670__aug1_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5670__aug2_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5670__aug3_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5670__aug4_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5670__aug5_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5670__aug6_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5670__aug7_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5670__aug8_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5670__aug9_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5679_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5679__aug10_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5679__aug1_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5679__aug2_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5679__aug3_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5679__aug4_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5679__aug5_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5679__aug6_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5679__aug7_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5679__aug8_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5679__aug9_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5800_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5800__aug10_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5800__aug1_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5800__aug2_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5800__aug3_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5800__aug4_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5800__aug5_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5800__aug6_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5800__aug7_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5800__aug8_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5800__aug9_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5803_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5803__aug10_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5803__aug1_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5803__aug2_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5803__aug3_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5803__aug4_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5803__aug5_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5803__aug6_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5803__aug7_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5803__aug8_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5803__aug9_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5840_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5840__aug10_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5840__aug1_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5840__aug2_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5840__aug3_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5840__aug4_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5840__aug5_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5840__aug6_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5840__aug7_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5840__aug8_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5840__aug9_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5910_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5910__aug10_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5910__aug1_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5910__aug2_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5910__aug3_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5910__aug4_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5910__aug5_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5910__aug6_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5910__aug7_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5910__aug8_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5910__aug9_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5921_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5921__aug10_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5921__aug1_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5921__aug2_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5921__aug3_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5921__aug4_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5921__aug5_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5921__aug6_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5921__aug7_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5921__aug8_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_5921__aug9_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_825_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_825__aug10_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_825__aug1_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_825__aug2_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_825__aug3_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_825__aug4_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_825__aug5_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_825__aug6_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_825__aug7_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_825__aug8_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_825__aug9_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_826_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_826__aug10_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_826__aug1_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_826__aug2_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_826__aug3_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_826__aug4_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_826__aug5_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_826__aug6_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_826__aug7_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_826__aug8_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_826__aug9_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_827_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_827__aug10_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_827__aug1_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_827__aug2_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_827__aug3_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_827__aug4_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_827__aug5_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_827__aug6_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_827__aug7_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_827__aug8_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_827__aug9_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_831_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_831__aug10_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_831__aug1_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_831__aug2_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_831__aug3_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_831__aug4_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_831__aug5_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_831__aug6_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_831__aug7_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_831__aug8_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_831__aug9_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_835_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_835__aug10_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_835__aug1_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_835__aug2_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_835__aug3_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_835__aug4_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_835__aug5_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_835__aug6_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_835__aug7_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_835__aug8_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_835__aug9_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_841_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_841__aug10_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_841__aug1_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_841__aug2_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_841__aug3_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_841__aug4_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_841__aug5_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_841__aug6_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_841__aug7_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_841__aug8_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_841__aug9_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_845_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_845__aug10_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_845__aug1_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_845__aug2_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_845__aug3_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_845__aug4_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_845__aug5_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_845__aug6_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_845__aug7_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_845__aug8_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_845__aug9_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_847_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_847__aug10_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_847__aug1_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_847__aug2_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_847__aug3_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_847__aug4_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_847__aug5_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_847__aug6_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_847__aug7_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_847__aug8_actions.pkl",
"/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_847__aug9_actions.pkl"]




rx = "v1_((\d+).*)_actions\.pkl"

uids = []
states = []

for i in range(len(actions)):
    uid = re.search(rx, actions[i]).group(1)
    uids.append(uid)

    base_uid = re.search(rx, actions[i]).group(2)
    print(uid, base_uid)
    state = "/data/nlahaye/NatureNet/Blue_Whale_v1/SWIRL_WHALE_v1_" + base_uid + "_states_abstract_env.pkl"    
    states.append(state)


pprint(states)

pprint(uids)


