python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_70.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_71.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_72.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_73.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_74.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_75.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_76.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_77.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_78.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_79.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_80.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_81.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_82.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_83.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_84.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_85.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_86.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_87.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_88.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_89.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_90.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_91.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_92.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_93.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_94.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_95.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_96.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_97.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_98.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_99.yaml

