python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_30.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_31.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_32.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_33.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_34.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_35.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_36.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_37.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_38.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_39.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_40.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_41.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_42.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_43.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_44.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_45.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_46.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_47.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_48.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_49.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_50.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_51.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_52.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_53.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_54.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_55.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_56.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_57.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_58.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_59.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_60.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_61.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_62.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_63.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_64.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_65.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_66.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_67.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_68.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_69.yaml


