python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_0.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_1.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_10.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_11.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_12.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_13.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_14.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_15.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_16.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_17.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_18.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_19.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_2.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_20.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_21.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_22.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_23.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_24.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_25.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_26.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_27.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_28.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_29.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_3.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_4.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_5.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_6.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_7.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_8.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_9.yaml

