python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_100.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_101.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_102.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_103.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_104.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_105.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_106.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_107.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_108.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_109.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_110.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_111.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_112.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_113.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_114.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_115.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_116.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_117.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_118.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_119.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_120.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_121.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_122.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_123.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_124.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_125.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_126.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_127.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_128.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_129.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_130.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_131.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_132.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_133.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_134.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_135.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_136.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_137.yaml
python3 surface_feature_connect.py  -y ../../config/environment/basic_env_setup_2NEW_SET_PREV_YEARS_138.yaml

